---
- 
  name: Installing lampstack using ansible
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Installing apache server
      apt: name={{ item }} state=present 
      with_items:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php

    - name: Start services
      service: name= {{ item }} state=started enabled=yes
      sudo: yes
      with_items:
        - apache2
        - mysql

    - name: Deploy static website
      sudo: yes
      copy:
        src: /home/siddharth/webdevelopment/Websiteusinghtml/index.html
        dest: /var/www/html/index.html
        remote_src: yes
